# Waze: User Churn Data (Hypothesis Testing Stage)

Case study from the Google Advanced Data Analytics Professional Certificate (Course 3: The Power of Statistics). Testing whether device type (iPhone vs. Android) is associated with ride activity.

## Plan

## Analyze and Construct

### Why descriptive statistics matter here

It lets get the feel of your data, to know the outliers, the missing values, the mean, median, to see if your data is trust worthy and to see if your data is actually good for the hypothesis test on it.

### Imports and data loading

In [1]:
# Import any relevant packages or libraries
import pandas as pd
import numpy as np
from scipy import stats

In [4]:
# Load dataset into dataframe
df = pd.read_csv('waze_dataset.csv')

### Data exploration

**Note:** In the dataset, `device` is a categorical variable with the labels `iPhone` and `Android`.

In order to perform this analysis, you must turn each label into an integer.  The following code assigns a `1` for an `iPhone` user and a `2` for `Android`.  It assigns this label back to the variable `device_new`.

**Note:** Creating a new variable is ideal so that you don't overwrite original data.

In [6]:
df.head()

,ID,label,sessions,drives,total_sessions,n_days_after_onboarding,total_navigations_fav1,total_navigations_fav2,driven_km_drives,duration_minutes_drives,activity_days,driving_days,device
0,0,retained,283,226,296.748273,2276,208,0,2628.845068,1985.775061,28,19,Android
1,1,retained,133,107,326.896596,1225,19,64,13715.920550,3160.472914,13,11,iPhone
2,2,retained,114,95,135.522926,2651,0,0,3059.148818,1610.735904,14,8,Android
3,3,retained,49,40,67.589221,15,322,7,913.591123,587.196542,7,3,iPhone
4,4,retained,84,68,168.247020,1562,166,5,3950.202008,1219.555924,27,18,Android

In [8]:
# 1. Create `map_dictionary`
map_dictionary = {"iPhone" : 1 , "Android" : 2}

# 2. Create new `device_type` column
# 3. Map the new column to the dictionary
df["device_type"] = df["device"].map(map_dictionary)
df

,ID,label,sessions,drives,total_sessions,n_days_after_onboarding,total_navigations_fav1,total_navigations_fav2,driven_km_drives,duration_minutes_drives,activity_days,driving_days,device,device_type
0,0,retained,283,226,296.748273,2276,208,0,2628.845068,1985.775061,28,19,Android,2
1,1,retained,133,107,326.896596,1225,19,64,13715.920550,3160.472914,13,11,iPhone,1
2,2,retained,114,95,135.522926,2651,0,0,3059.148818,1610.735904,14,8,Android,2
3,3,retained,49,40,67.589221,15,322,7,913.591123,587.196542,7,3,iPhone,1
4,4,retained,84,68,168.247020,1562,166,5,3950.202008,1219.555924,27,18,Android,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14994,14994,retained,60,55,207.875622,140,317,0,2890.496901,2186.155708,25,17,iPhone,1
14995,14995,retained,42,35,187.670313,2505,15,10,4062.575194,1208.583193,25,20,Android,2
14996,14996,retained,273,219,422.017241,1873,17,0,3097.825028,1031.278706,18,17,iPhone,1
14997,14997,churned,149,120,180.524184,3150,45,0,4051.758549,254.187763,6,6,iPhone,1
14998,14998,retained,73,58,353.419797,3383,13,51,6030.498773,3042.436423,14,13,iPhone,1

You are interested in the relationship between device type and the number of drives. One approach is to look at the average number of drives for each device type. Calculate these averages.

In [9]:
df.groupby("device")["drives"].mean()

device
Android    66.231838
iPhone     67.859078
Name: drives, dtype: float64

Based on the averages shown, it appears that drivers who use an iPhone device to interact with the application have a higher number of drives on average. However, this difference might arise from random sampling, rather than being a true difference in the number of drives. To assess whether the difference is statistically significant, you can conduct a hypothesis test.

### Hypothesis testing

Recall the difference between the null hypothesis ($H_0$) and the alternative hypothesis ($H_A$).

**Question:** What are your hypotheses for this data project?

H0 : there is no difference in mean amount of rides between iPhone users and Android users.

HA : there is difference in mean amount of rides between iPhone users and Android users.

Next, choose 5% as the significance level and proceed with a two-sample t-test.

You can use the `stats.ttest_ind()` function to perform the test.


**Technical note**: The default for the argument `equal_var` in `stats.ttest_ind()` is `True`, which assumes population variances are equal. This equal variance assumption might not hold in practice (that is, there is no strong reason to assume that the two groups have the same variance); you can relax this assumption by setting `equal_var` to `False`, and `stats.ttest_ind()` will perform the unequal variances $t$-test (known as Welch's `t`-test). Refer to the [scipy t-test documentation](https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.ttest_ind.html) for more information.


1. Isolate the `drives` column for iPhone users.
2. Isolate the `drives` column for Android users.
3. Perform the t-test

In [10]:
# 1. Isolate the `drives` column for iPhone users.
drives_iphone = df[df["device"] == "iPhone"]

# 2. Isolate the `drives` column for Android users.
drives_android = df[df["device"] == "Android"]

# 3. Perform the t-test
stats.ttest_ind(a=drives_iphone["drives"], b=drives_android["drives"], equal_var=False)

Ttest_indResult(statistic=1.4635232068852353, pvalue=0.1433519726802059)

**Question:** Based on the p-value you got above, do you reject or fail to reject the null hypothesis?

0.14 > 0.05, hence we failed to reject the null hypothesis that states that "there is no difference in mean amount of rides between iPhone users and Android users."

## Execute

### Communicate insights with stakeholders

No statistically significant difference in average ride count between iPhone and Android users device type alone isn't a meaningful factor for explaining ride behavior, so maybe other variables are worth investigating instead.